youth = ["lihongrui", "liuweiwei", "chengcheng", "liuxiuxiu", "maoxihui", "liuxiaohang", "wangxingming"]

print(youth[0] + ", Please have dinner with me.")
print(youth[1] + ", Please have dinner with me.")
print(youth[2] + ", Please have dinner with me.")
print(youth[3] + ", Please have dinner with me.")
print(youth[4] + ", Please have dinner with me.")
print(youth[5] + ", Please have dinner with me.")
print(youth[6] + ", Please have dinner with me.")

youth.insert(0, "chengliudang")
youth.insert(2, "wenjing")
youth.append("liaoxiaoling")

print("\n")
print(youth[0] + ", Please have dinner with me.")
print(youth[1] + ", Please have dinner with me.")
print(youth[2] + ", Please have dinner with me.")
print(youth[3] + ", Please have dinner with me.")
print(youth[4] + ", Please have dinner with me.")
print(youth[5] + ", Please have dinner with me.")
print(youth[6] + ", Please have dinner with me.")
print(youth[7] + ", Please have dinner with me.")
print(youth[8] + ", Please have dinner with me.")
print(youth[9] + ", Please have dinner with me.")
